default_agent: test_multi_framework
agents:
  test_multi_framework:
    name: test_multi_framework
    entrypoint: src/main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::570214690808:role/AmazonBedrockAgentCoreSDKRuntime-test_multi_framework
      execution_role_auto_create: true
      account: '570214690808'
      region: us-east-1
      ecr_repository: 570214690808.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-test_multi_framework
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: test_multi_framework-0YQXic33NV
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:570214690808:runtime/test_multi_framework-0YQXic33NV
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
